version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.11.9
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+psycopg://dovah:dovah@postgres:5432/dovah
      - POSTGRES_URL=postgresql+psycopg://dovah:dovah@postgres:5432/dovah
      - DOVAH_TENANT_SALT=dev_only_do_not_use
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: dovah
      POSTGRES_PASSWORD: dovah
      POSTGRES_DB: dovah
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dovah"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
