version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: dovah
      POSTGRES_PASSWORD: dovah
      POSTGRES_DB: dovah
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dovah"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
