name: dovah
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas=2.2.*
  - numpy=1.26.*
  - scikit-learn=1.5.*
  - requests>=2.32
  - pydantic=2.8.*
  - sqlalchemy=2.0.*
  - alembic=1.13.*
  - psycopg=3.1.*
  - pytest=8.*
  - pytest-cov=5.*
  - mypy=1.11.*
  - ruff=0.5.*
  - black=24.*
  - pre-commit=3.7.*
  - scipy=1.13.*
  - matplotlib=3.9.*
  - seaborn=0.13.*
  - networkx=3.2.*
  - python-louvain=0.16.*  # For community detection
  - statsmodels=0.14.*     # For time series analysis
  - pip:
      - pgvector==0.2.5
      - drain3==0.9.11
      - tenacity==8.2.3
      - fastdtw==0.3.4      # For time series similarity
