name: Phase 3 — Workability Check

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  phase3:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install project (editable) + deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt || true; fi

      - name: Run unit tests (quiet)
        run: python -m pytest -q

      # Run your Phase 3 pipeline + acceptance gate WITHOUT conda
      - name: Phase 3 pipeline + gate (p95 < 800 ms)
        run: make phase3-all PHASE=phase3 PY=python SH="sh -c"

      - name: Show p95
        if: always()
        run: |
          test -f reports/phase3/p95.txt && cat reports/phase3/p95.txt || echo "p95.txt not found"

      - name: Upload Phase 3 artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: phase3-artifacts
          path: reports/phase3/**/*
          if-no-files-found: warn
